// @ts-check
/**

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  kardSidebar: [
    {
      type: 'autogenerated',
      dirName: '.'
    }
  ],
};

export default sidebars;
